[workspace]
members = [
    ".",
    "ops-core",
]

[package]
name = "ops"
description = "Adds operational endpoints to your application"
repository = "https://github.com/uw-labs/rust-ops"
version = "0.1.0"
authors = ["rustaceans <rustaceans@utilitywarehouse.co.uk>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/ops/"

[dependencies]
hyper = "0.13"
once_cell = "1"
ops-core = { path = "./ops-core" }
prometheus = { version = "0.9", default-features = false, features = ["process"] }
rayon = "1"
serde_json = { version = "1" }

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
